### ISSUE TITLE
I cant have 2 different markdown files open.

### ISSUE THREAD

**Issue by jhicken** [keshann93/markdown-live#40]
So I have 2 markdown files one in a dot folder and the README.md If I open one when I try to open the other weird things happen.

Sometimes it jumps back to the first file I had open. Sometimes it shows the second file, but the editor seems broken on the second file because nothing is displayed in the editor view.

**Comment by sagebind** [comment]
Same here; I really like the idea of the extension but whenever I try to open a second Markdown file, it glitches out and switches tabs automatically to the first one. Unfortunately I couldn't find any relevant logs or errors in the vscode console. Disabling all other extensions also did not help.

**Comment by keshann93** [comment]
Hi there! @jhicken @sagebind thank you for trying out the extension. I have revamped the extension to support multiple files do checkout the readme and update the extension to see the new changes. Do let me know if anything else can be improved. Have a good day!

**Comment by keshann93** [comment]
I am closing this issue, since there wan't any concern raised
