### ISSUE TITLE
Mac keyboard shortcuts stomp on default keybindings

### ISSUE THREAD

**Issue by swrobel** [keshann93/markdown-live#57]
Full list of Mac keybindings available on [this PDF](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf). Example of problematic keybinding: ⌥⌘S should "Save All" but "Markdown Live" steals it. I haven't gone through to check all of the others to see if they're conflicting, but I happen to use "Save All" pretty often.

Sidenote: I love this extension - thank you so much for building it!

**Comment by keshann93** [comment]
@swrobel  keybinding is changed from `cmd+alt+s` to `cmd+alt+r` for strike function. please try out the new version of the extension it comes with more changes towards the usability perspective
