### ISSUE TITLE
Can't find in file

### ISSUE THREAD

**Issue by swrobel** [keshann93/markdown-live#58]
No ability to find/replace as far as I can tell

**Comment by keshann93** [comment]
Hi @swrobel  thank you for trying out the extension! I have revamped the extension after observing people are facing issues when the extension tries to replace the normal text editor which lets the users with the option of only using the extension editor which seems buggy.

I came up with the solution to make the extension editor an optional one, where user can use it as a second column to quickly view or edit the markdown files with the aid of the extension. check **Readme** and update the extension to see the changes. Do let me know how you feel the new change and any-other constructive feedback are most welcome! Have a great day!

**Comment by swrobel** [comment]
@keshann93 this definitely solves my issue, although I do wish I could just use the WYSIWYG editor and find in files, although I know that's probably a lot more work. It does seem there are no longer any extension options - I would particularly at least like one to open the second column automatically when a markdown file is opened.

**Comment by keshann93** [comment]
@swrobel Thank you! the description you provided above illustrates the motivation behind this project. Do star it if you like, that would motivate me to try more! I am closing this issue
